services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ddd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  kurrentdb:
    image: kurrentplatform/kurrentdb:25.0.1-experimental-arm64-8.0-jammy
    ports:
      - "2113:2113"
    environment:
      - KURRENTDB_CLUSTER_SIZE=1
      - KURRENTDB_RUN_PROJECTIONS=All
      - KURRENTDB_START_STANDARD_PROJECTIONS=true
      - KURRENTDB_NODE_PORT=2113
      - KURRENTDB_INSECURE=true
      - KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP=true
    volumes:
      - type: volume
        source: kurrentdb-volume-data
        target: /var/lib/kurrentdb
      - type: volume
        source: kurrentdb-volume-logs
        target: /var/log/kurrentdb

volumes:
  postgres-data:
  kurrentdb-volume-data:
  kurrentdb-volume-logs:
