spring:
  profiles:
    active: local
  application:
    name: ddd-demo
  datasource:
    task:
      url: ${TASK_DATASOURCE_URL}
      username: ${TASK_DATASOURCE_USERNAME}
      password: ${TASK_DATASOURCE_PASSWORD}
  data:
    jdbc:
      repositories:
        enabled: false
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}

services:
  identity-access:
    url: http://localhost:8080

environment:
  identity_access:
    access_token:
      secret: secret
      expires_in: 3600 # 1時間
    refresh_token:
      secret: secret
      expires_in: 3456000 # 30日
