spring:
  application:
    name: ddd-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/ddd
    username: user
    password: password
  flyway:
    user: user
    password: password

  jpa:
    show-sql: true

services:
  identity-access:
    url: http://localhost:8080

environment:
  identity_access:
    access_token:
      secret: secret
      expires_in: 3600 # 1時間
    refresh_token:
      secret: secret
      expires_in: 3456000 # 30日
