CREATE TABLE ddd_user (
  user_id VARCHAR(36) PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by TEXT NOT NULL DEFAULT CURRENT_USER,
  updated_by TEXT NOT NULL DEFAULT CURRENT_USER
);

CREATE TRIGGER trigger_set_audit_columns
    BEFORE INSERT OR UPDATE ON ddd_user
    FOR EACH ROW
    EXECUTE FUNCTION set_audit_columns();

